### PR TITLE
fix: fix typos

### LINKED ISSUE #38: Fix typos
There are several typos and grammar errors throughout the docs.

Examples:

1. https://docs.openbeta.io/project-ideas/software-dev
  First _ascenionists_ (FA) played a vital role in the development of rock climbing.
2. https://docs.openbeta.io/faq
  Oftentimes it's the work of multiple contributors and a mix of creative, and factual and _non-copyritable_ content.
3. Sidebar title:
  Good PR _Guideline_ - should be _Guidelines_

### PR DESCRIPTION
**Pull request by draykhlin**
This PR resolves #38 .

Fixed several typos and grammar errors throughout the documentation.

### CODE REVIEW

**Comment by draykhlin** [comment]
Sorry, it looks like I accidentally committed a bunch of yarn files - I'm not sure how to resolve this.

**Comment by musoke** [comment]
you've already done the right thing by adding them to the .gitignore.

To remove them, run
```
git rm -r .yarn*
git commit
```
However, they will still be in history as first added, then removed.

To remove them from history completely, use `git rebase -i HEAD~6` to reorder and combine commits.  You'll see an editor window with content like this pop up
```
pick 4bc02ad fixed typos
pick ece9dd8 fixed additional typos and grammar errors
pick 79ef2b3 fixed additional typo
pick 9f81b59 fixed additional typo
pick 5bde72a added yarn to gitignore
pick b2e600a remove .yarn                                                                          #new commit that removes yarn files

# Rebase 3082b4e..b2e600a onto 9f81b59 (6 commands)
#
# Commands:
# p, pick <commit> = use commit
# r, reword <commit> = use commit, but edit the commit message
# e, edit <commit> = use commit, but stop for amending
# s, squash <commit> = use commit, but meld into previous commit
# f, fixup <commit> = like "squash", but discard this commit's log message
# x, exec <command> = run command (the rest of the line) using shell
# b, break = stop here (continue rebase later with 'git rebase --continue')
# d, drop <commit> = remove commit
# l, label <label> = label current HEAD with a name
# t, reset <label> = reset HEAD to a label
# m, merge [-C <commit> | -c <commit>] <label> [# <oneline>]
# .       create a merge commit using the original merge commit's
# .       message (or the oneline, if no original merge commit was
# .       specified). Use -c <commit> to reword the commit message.
#
# These lines can be re-ordered; they are executed from top to bottom.
#
# If you remove a line here THAT COMMIT WILL BE LOST.
#
# However, if you remove everything, the rebase will be aborted.
#
# Note that empty commits are commented out
```

Change the first lines to 
```
pick 4bc02ad fixed typos
fixup b2e600a remove .yarn
fixup ece9dd8 fixed additional typos and grammar errors
fixup 79ef2b3 fixed additional typo
fixup 9f81b59 fixed additional typo
pick 5bde72a added yarn to gitignore

```
by moving your new commit up to the second and then changing the commands for all but the first and list to "fixup".  The command "fixup" tells git to combine a commit into the previous one.  

In the end, running 
```
git log --patch
```
will show you the new history.  You should see two commits: one with all your typo fixes and one with your addition to .gitignore.  Check that everything is there and looks right.
If that all looks good, run
```
git push --force
```
to **overwrite** your current changes here with the new ones, now without the extra files and in only two commits.

**Comment by draykhlin** [comment]
Thanks for the detailed instructions @musoke! It should be all set now.

**Comment by draykhlin** [comment]
Sorry, this is my first time contributing and I'm a bit confused as to how gitignore should be handled. I noticed my addition of /.yarn to the gitignore was included in the commit - is this correct or should it be excluded?

**Review by vnugent — APPROVED** [review]

**Pull request merged**
